<?php

namespace Database\Seeders;

use App\Models\View;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ViewsTableSeeder extends Seeder
{
    use WithoutModelEvents;

    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $views = [
            [
                'id' => 1,
                'parent_id' => null,
                'name' => 'Dashboard',
                'slug' => 'dashboard',
                'route' => 'dashboard',
                'icon' => 'LayoutDashboard',
                'description' => 'Indicadores del proceso de admisión',
                'order' => 1,
                'is_active' => true,
            ],
            [
                'id' => 2,
                'parent_id' => null,
                'name' => 'Procesos',
                'slug' => 'procesos',
                'route' => 'procesos',
                'icon' => 'LucideWorkflow',
                'description' => 'Gestiona los proceso de admisión',
                'order' => 2,
                'is_active' => true,
            ],
            [
                'id' => 3,
                'parent_id' => null,
                'name' => 'Archivos TXT',
                'slug' => 'archivos-txt',
                'route' => 'archivos-txt',
                'icon' => 'FileText',
                'description' => 'Subir archivos txt del banco de la nación',
                'order' => 3,
                'is_active' => true,
            ],
            [
                'id' => 4,
                'parent_id' => null,
                'name' => 'Pagos Banco',
                'slug' => 'pagos-banco',
                'route' => 'pagos-banco',
                'icon' => 'CreditCard',
                'description' => 'Pagos de postulantes al banco de la nación',
                'order' => 4,
                'is_active' => true,
            ],
            [
                'id' => 5,
                'parent_id' => null,
                'name' => 'Postulantes',
                'slug' => 'postulantes',
                'route' => 'postulantes',
                'icon' => 'Users',
                'description' => 'Gestiona los postulantes al examen de admisión',
                'order' => 5,
                'is_active' => true,
            ],
            [
                'id' => 6,
                'parent_id' => null,
                'name' => 'Distribución de Vacantes',
                'slug' => 'distribucion-de-vacantes',
                'route' => 'distribucion-vacantes',
                'icon' => 'Grid3X3',
                'description' => 'Distribución de Vacantes',
                'order' => 6,
                'is_active' => true,
            ],
            [
                'id' => 7,
                'parent_id' => null,
                'name' => 'Enviar Correos',
                'slug' => 'enviar-correos',
                'route' => 'enviar-correos',
                'icon' => 'LucideMail',
                'description' => 'Enviar Correos',
                'order' => 7,
                'is_active' => true,
            ],
            [
                'id' => 8,
                'parent_id' => 7,
                'name' => 'Válidos',
                'slug' => 'validos',
                'route' => 'validos',
                'icon' => 'CheckCircle',
                'description' => 'Válidos',
                'order' => 8,
                'is_active' => true,
            ],
            [
                'id' => 9,
                'parent_id' => 7,
                'name' => 'Observados',
                'slug' => 'observados',
                'route' => 'observados',
                'icon' => 'AlertCircle',
                'description' => 'Observados',
                'order' => 9,
                'is_active' => true,
            ],
            [
                'id' => 10,
                'parent_id' => 7,
                'name' => 'Reitero Observados',
                'slug' => 'reitero-observados',
                'route' => 'reitero',
                'icon' => 'LucideRefreshCw',
                'description' => 'Reitero Observados',
                'order' => 10,
                'is_active' => true,
            ],
            [
                'id' => 11,
                'parent_id' => 7,
                'name' => 'Rectificados',
                'slug' => 'rectificados',
                'route' => 'rectificados',
                'icon' => 'FileCheck',
                'description' => 'Rectificados',
                'order' => 11,
                'is_active' => true,
            ],
            [
                'id' => 12,
                'parent_id' => null,
                'name' => 'Maestros',
                'slug' => 'maestros',
                'route' => 'maestros',
                'icon' => 'Database',
                'description' => 'Maestros',
                'order' => 12,
                'is_active' => true,
            ],
            [
                'id' => 13,
                'parent_id' => 12,
                'name' => 'Exámenes',
                'slug' => 'examenes',
                'route' => 'examenes',
                'icon' => 'ClipboardList',
                'description' => 'Exámenes',
                'order' => 13,
                'is_active' => true,
            ],
            [
                'id' => 14,
                'parent_id' => 12,
                'name' => 'Modalidades',
                'slug' => 'modalidades',
                'route' => 'modalidades',
                'icon' => 'ListChecks',
                'description' => 'Modalidades',
                'order' => 14,
                'is_active' => true,
            ],
            [
                'id' => 15,
                'parent_id' => 12,
                'name' => 'Sedes',
                'slug' => 'sedes',
                'route' => 'sedes',
                'icon' => 'LucideMapPin',
                'description' => 'Sedes',
                'order' => 15,
                'is_active' => true,
            ],
            [
                'id' => 16,
                'parent_id' => 12,
                'name' => 'Facultades',
                'slug' => 'facultades',
                'route' => 'facultades',
                'icon' => 'Landmark',
                'description' => 'Facultades',
                'order' => 16,
                'is_active' => true,
            ],
            [
                'id' => 17,
                'parent_id' => 12,
                'name' => 'Grupos Académicos',
                'slug' => 'grupos-academicos',
                'route' => 'grupos-academicos',
                'icon' => 'Layers',
                'description' => 'Grupos Académicos',
                'order' => 17,
                'is_active' => true,
            ],
            [
                'id' => 18,
                'parent_id' => 12,
                'name' => 'Programas Académicos',
                'slug' => 'programas-academicos',
                'route' => 'programas-academicos',
                'icon' => 'BookMarked',
                'description' => 'Programas Académicos',
                'order' => 18,
                'is_active' => true,
            ],
            [
                'id' => 19,
                'parent_id' => 12,
                'name' => 'Universidades',
                'slug' => 'universidades',
                'route' => 'universidades',
                'icon' => 'GraduationCap',
                'description' => 'Universidades',
                'order' => 19,
                'is_active' => true,
            ],
            [
                'id' => 20,
                'parent_id' => 12,
                'name' => 'Colegios',
                'slug' => 'colegios',
                'route' => 'colegios',
                'icon' => 'LucideSchool',
                'description' => 'Colegios',
                'order' => 20,
                'is_active' => true,
            ],
            [
                'id' => 21,
                'parent_id' => 12,
                'name' => 'Estados de Postulante',
                'slug' => 'estados-de-postulante',
                'route' => 'estados-postulante',
                'icon' => 'Flag',
                'description' => 'estados-postulante',
                'order' => 21,
                'is_active' => true,
            ],
            [
                'id' => 22,
                'parent_id' => 12,
                'name' => 'Tipos de Direcciones',
                'slug' => 'tipos-de-direcciones',
                'route' => 'tipos-direcciones',
                'icon' => 'Home',
                'description' => 'Tipos de Direcciones',
                'order' => 22,
                'is_active' => true,
            ],
            [
                'id' => 23,
                'parent_id' => 12,
                'name' => 'Géneros',
                'slug' => 'generos',
                'route' => 'generos',
                'icon' => 'LucideUser2',
                'description' => 'Géneros',
                'order' => 23,
                'is_active' => true,
            ],
            [
                'id' => 24,
                'parent_id' => 12,
                'name' => 'Distritos',
                'slug' => 'distritos',
                'route' => 'distritos',
                'icon' => 'LucideMap',
                'description' => 'Distritos',
                'order' => 24,
                'is_active' => true,
            ],
            [
                'id' => 25,
                'parent_id' => 12,
                'name' => 'Países',
                'slug' => 'paises',
                'route' => 'paises',
                'icon' => 'Globe',
                'description' => 'Países',
                'order' => 25,
                'is_active' => true,
            ],
            [
                'id' => 26,
                'parent_id' => null,
                'name' => 'Configuración',
                'slug' => 'configuracion',
                'route' => 'configuracion',
                'icon' => 'Settings',
                'description' => 'Configuración',
                'order' => 26,
                'is_active' => true,
            ],
            [
                'id' => 27,
                'parent_id' => 26,
                'name' => 'Vistas',
                'slug' => 'vistas',
                'route' => 'vistas',
                'icon' => 'LucideMonitorCog',
                'description' => 'Vistas',
                'order' => 27,
                'is_active' => true,
            ],
            [
                'id' => 28,
                'parent_id' => 26,
                'name' => 'Roles',
                'slug' => 'roles',
                'route' => 'roles',
                'icon' => 'LucideShieldCheck',
                'description' => 'Roles',
                'order' => 28,
                'is_active' => true,
            ],
            [
                'id' => 29,
                'parent_id' => null,
                'name' => 'Usuarios',
                'slug' => 'usuarios',
                'route' => 'usuarios',
                'icon' => 'LucideUserCog',
                'description' => 'Usuarios',
                'order' => 29,
                'is_active' => true,
            ],
        ];

        foreach ($views as $viewData) {
            View::updateOrCreate(
                ['id' => $viewData['id']],
                $viewData
            );
        }

        $this->command->info('Views seeded successfully!');
    }
}
